runners:
  # https://runs-on.com/features/custom-runners/
  # https://aws.amazon.com/ec2/instance-types/
  2cpu-4ram:
    cpu: 2
    ram: 4
    family: ["c8g"]
    hdd: 40
    image: ubuntu24-full-arm64
    extras: s3-cache
    spot: lowest-price
    ssh: false
  2cpu-8ram:
    cpu: 2
    ram: 16 # temporarily use 16 GiBs of ram becasue mg8 machine is not available in our current RunsOn AWS region.
    family: ["r8g"]
    hdd: 40
    image: ubuntu24-full-arm64
    extras: s3-cache
    spot: lowest-price
    ssh: false
