name: Perform public API breakage check for Swift package
description: Encapsulates the steps for running the package pubilc API breakage checker provided by Swift Package Manager.

inputs:
  baseline_ref:
    required: false
    default: 'origin/main'
    description: "A git ref to use as the baseline API."
  allowlist_path:
    required: false
    default: ''
    description: "A repo-relative path containing API breakage diagnostics to be ignored."
  extra_flags:
    required: false
    default: ''
    description: "Additional 'swift package diagnose-api-breaking-changes' flags."
  targets:
    required: false
    default: ''
    description: "Space-separated list of specific targets to diagnose."
  package_root:
    required: false
    default: ''
    description: "Run the API check at a given path rather than the current directory."

runs:
  using: composite
  steps:
      # https://github.com/actions/checkout/issues/766
      - name: Mark the Git workspace safe
        shell: bash
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Perform API breakage check
        shell: bash
        env:
          TARGETS:        ${{ inputs.targets != ''        && format('--targets={0}', inputs.targets) || '' }}
          PACKAGE_ROOT:   ${{ inputs.package_root != ''   && format('--package-path={0}', inputs.package_root) || '' }}
          ALLOWLIST_PATH: ${{ inputs.allowlist_path != '' && format('--breakage-allowlist-path={0}', inputs.allowlist_path) || '' }}
          BASELINE_REF:   ${{ inputs.baseline_ref }}
          EXTRA_FLAGS:    ${{ inputs.extra_flags }}
        run: |
          swift package ${PACKAGE_ROOT} diagnose-api-breaking-changes \
              "${BASELINE_REF}" ${EXTRA_FLAGS} ${TARGETS} ${ALLOWLIST_PATH}
