name: Self-test the reusable workflow
on:
  workflow_dispatch:
    inputs:
      with_gh_codeql:
        type: boolean
        required: false
        default: true
        description: "Set to 'true' to run CodeQL checks. Defaults to 'true'."
  push: { branches: [ main ] }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: ./.github/workflows/run-unit-tests.yml
    with:
      with_coverage: ${{ inputs.with_coverage || false }}
      with_tsan: ${{ inputs.with_tsan || false }}
      with_api_check: true
      with_gh_codeql: ${{ inputs.with_gh_codeql || true }}
      warnings_as_errors: true
      with_linting: true
      with_windows: true
      with_musl: true
      ios_scheme_name: sample-testable-package
