name: Test of reusable workflow

on:
  pull_request:
    paths:
      - '.github/workflows/run-unit-tests.yml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/run-unit-tests.yml'
  workflow_dispatch:

jobs:

  test-workflow-all_params:
    uses: ${{ format('vapor/ci/run-unit-tests.yml@{0}', github.ref_name) }}
    with:
      subpath: sample-testable-package
      with_coverage: false
      with_tsan: false
      test_filter: '^S'
      test_skip: '^Z'
      extra_flags: '-c debug'
      extra_flags_linux: '--netrc-optional'
      extra_flags_macos: '--disable-sandbox'
      extra_flags_windows: '--verbose'

  test-workflow-cov_tsan:
    uses: ${{ format('vapor/ci/run-unit-tests.yml@{0}', github.ref_name) }}
    with:
      subpath: sample-testable-package
      with_coverage: true
      with_tsan: true

  test-workflow-cov:
    uses: ${{ format('vapor/ci/run-unit-tests.yml@{0}', github.ref_name) }}
    with:
      subpath: sample-testable-package
      with_coverage: true
      with_tsan: false

  test-workflow-tsan:
    uses: ${{ format('vapor/ci/run-unit-tests.yml@{0}', github.ref_name) }}
    with:
      subpath: sample-testable-package
      with_coverage: false
      with_tsan: true

  test-workflow-plain:
    uses: ${{ format('vapor/ci/run-unit-tests.yml@{0}', github.ref_name) }}
    with:
      subpath: sample-testable-package
      with_coverage: false
      with_tsan: false

  test-workflow-defaults:
    uses: ${{ format('vapor/ci/run-unit-tests.yml@{0}', github.ref_name) }}
    with:
      subpath: sample-testable-package
