name: appropriate-issues-to-appropriate-boards
on:
  workflow_call:
    secrets:
      PROJECT_BOARD_AUTOMATION_PAT:
        required: true

jobs:
  handle_labeling_events:
    strategy:
      fail-fast: false
      matrix:
        include:
          - label: "good first issue"
            board: "Beginner Issues"
          - label: "help wanted"
            board: "Help Wanted Issues"
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update Card
        # When handling label/unlabel events, the specific label in question is given by the event.
        # When handling other issue events, we only care whether the issue has the appropriate label in general.
        if: |
          (
            contains(fromJSON('["labeled", "unlabeled"]'), github.event.action) &&
            matrix.label == github.event.label.name
          ) || (
            contains(fromJSON('["assigned", "unassigned", "reopened", "closed"]'), github.event.action) &&
            contains(github.event.issue.labels.*.name, matrix.label)
          )
        uses: alex-page/github-project-automation-plus@main
        with:
          # - When an issue is assigned, we want to move it to "In progress"
          # - When an issue is closed, we want to move it to "Done"
          # - When an issue loses a label, we don't care what the column is (see "action" below)
          # - For all other events, we want to create a card in, or move an existing one to, "To do"
          column: ${{ (github.event.action == 'assigned' && 'In progress') || (github.event.action == 'closed' && 'Done') || 'To do' }}
          # - For unlabeling events, we want to delete the card completely
          # - In all other cases, we want to create if not exists, update if it does ("update" correctly does this)
          action: ${{ (github.event.action == 'unlabeled' && 'delete') || 'update' }}
          project: ${{ matrix.board }}
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_PAT }}
